name: Groovy Linting

on: [push] # Trigger the workflow on push events

jobs:
  lint:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Checks out your repository's code

    - name: Run Groovy linting
      uses: docker://nvuillam/npm-groovy-lint:9.3 # Use the Docker image for linting
      with:
        args: npm-groovy-lint --no-insight --noserver Jenkinsfile # Specify the command and arguments
