name: Groovy Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create linting configuration file
      run: echo '{"extends":"recommended","rules":{"LineLength":{"enabled":false},"NestedBlockDepth":{"enabled":false}}}' > lint_config.json

    - name: Run Groovy linting
      uses: docker://nvuillam/npm-groovy-lint:9.3
      with:
        args: npm-groovy-lint --no-insight --noserver -c lint_config.json
